import time
print("Write a noun.")
    noun1 = input()
print("Write another noun")
    noun2 = input()
print("Write an adjective.")
    adjective1 = input()
print("Write a verb.")
verb1 = input()
print("Verb")
verb2 = input()
print("Verb")
verb3 = input()
print("Plural noun")
pluralnoun1 = input()
print("Verb")
verb4 = input()
print("Verb")
verb5 = input()
print("Verb")
verb6 = input()
print("Verb")
verb7 = input()
print("Noun")
noun3 = input()
print("Noun")
noun4 = input()
print("Noun")
noun5 = input()
print("Verb in past tense")
pasttense1 = input()
print("Verb in past tense")
pasttense2 = input()
print("Verb in past tense")
pasttense3 = input()
print("Verb in past tense")
pasttense4 = input()
print("Verb in past tense")
pasttense5 = input()
print("Verb in past tense")
pasttense6 = input()
print("Plural noun")
pluralnoun2 = input()
print("Plural noun")
pluralnoun3 = input()
print("Adjective")
adjective2



